[workspace]
authors = ["GrCOTE7 <grcote7@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
main = 'ls *.mojo | entr -r pixi run mojo run main.mojo'
list_all = 'ls -l *.mojo'
# pymojo = 'ls *.py | entr -r pixi run python3 pymojo.py'

[dependencies]
modular = ">=25.5.0.dev2025070905,<26"

[pypi-dependencies]
flet = { version = "==0.28.3", extras = ["all"] }
